[project]
name = "rmakan-anly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic==1.17.0",
    "annotated-types==0.7.0",
    "anyio==4.11.0",
    "bcrypt==4.3.0",
    "certifi==2025.10.5",
    "cffi==2.0.0",
    "click==8.3.0",
    "colorama==0.4.6",
    "cryptography==46.0.2",
    "dependencies==7.7.1",
    "deprecation==2.1.0",
    "dnspython==2.8.0",
    "ecdsa==0.19.1",
    "email-validator==2.3.0",
    "fastapi==0.119.0",
    "greenlet==3.2.4",
    "h11==0.16.0",
    "h2==4.3.0",
    "hpack==4.1.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "hyperframe==6.1.0",
    "idna==3.11",
    "iniconfig==2.1.0",
    "jose==1.0.0",
    "jwt==1.4.0",
    "lock==2018.3.25.2110",
    "mako==1.3.10",
    "markdown-it-py==4.0.0",
    "markupsafe==3.0.3",
    "mdurl==0.1.2",
    "multidict==6.7.0",
    "packaging==25.0",
    "passlib==1.7.4",
    "pip==25.2",
    "pluggy==1.6.0",
    "postgrest==2.22.0",
    "propcache==0.4.1",
    "psycopg2==2.9.11",
    "pyasn1==0.6.1",
    "pycparser==2.23",
    "pydantic-core==2.41.1",
    "pydantic[email]==2.12.0",
    "pygments==2.19.2",
    "pyjwt==2.10.1",
    "pytest==8.4.2",
    "python-dotenv==1.1.1",
    "python-jose==3.5.0",
    "python-multipart==0.0.20",
    "realtime==2.22.0",
    "rich==14.2.0",
    "rsa==4.9.1",
    "setuptools==80.9.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.44",
    "starlette==0.48.0",
    "storage3==2.22.0",
    "strenum==0.4.15",
    "supabase==2.22.0",
    "supabase-auth==2.22.0",
    "supabase-functions==2.22.0",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "uvicorn==0.37.0",
    "websockets==15.0.1",
    "yarl==1.22.0",
]
