"""set status default jadi pending

Revision ID: 549a92322fc1
Revises: f7010154a7eb
Create Date: 2025-09-26 14:48:34.835935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549a92322fc1'
down_revision: Union[str, Sequence[str], None] = 'f7010154a7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', name='reservationstatusenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', name='reservationstatusenum'),
               nullable=True)
    # ### end Alembic commands ###
