"""ganti table_number jadi kode_meja

Revision ID: 6a572c5ccac2
Revises: 90fbcdef2187
Create Date: 2025-10-14 13:09:20.702456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a572c5ccac2'
down_revision: Union[str, Sequence[str], None] = '90fbcdef2187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meja', 'kode_meja', existing_type=sa.Integer(), type_=sa.String(), existing_nullable=False)
    op.drop_constraint('meja_table_number_key', 'meja', type_='unique')
    op.create_unique_constraint('meja_kode_meja_key', 'meja', ['kode_meja'])
    op.alter_column('reservation', 'reservation_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'reservation_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('meja', sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meja', type_='unique')
    op.create_unique_constraint(op.f('meja_table_number_key'), 'meja', ['table_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('meja', 'kode_meja')
    # ### end Alembic commands ###
