"""create reservasi table

Revision ID: 737ceb403d09
Revises: 549a92322fc1
Create Date: 2025-10-06 05:50:10.108534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737ceb403d09'
down_revision: Union[str, Sequence[str], None] = '549a92322fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('id_staff', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'users', ['id_staff'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'id_staff')
    # ### end Alembic commands ###
