""" status di reservasi ditambahkan completed

Revision ID: 90fbcdef2187
Revises: 9df251a2bdce
Create Date: 2025-10-13 14:01:01.756766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fbcdef2187'
down_revision: Union[str, Sequence[str], None] = '9df251a2bdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE reservationstatusenum ADD VALUE IF NOT EXISTS 'completed';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE reservationstatusenum_old AS ENUM ('pending', 'confirmed', 'cancelled');
        ALTER TABLE reservation ALTER COLUMN status TYPE reservationstatusenum_old USING status::text::reservationstatusenum_old;
        DROP TYPE reservationstatusenum;
        ALTER TYPE reservationstatusenum_old RENAME TO reservationstatusenum;
    """)

    # ### end Alembic commands ###
