"""Mengubah id jadi uuid di user table

Revision ID: 924cf9e8efb1
Revises: 20f332f281c7
Create Date: 2025-10-14 13:36:53.441998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '924cf9e8efb1'
down_revision: Union[str, Sequence[str], None] = '20f332f281c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    # Tambah kolom UUID baru di users
    op.add_column('users', sa.Column('id_new', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute('UPDATE users SET id_new = gen_random_uuid();')

    # Hapus foreign key lama
    op.drop_constraint('feedback_id_users_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('reservation_id_staff_fkey', 'reservation', type_='foreignkey')
    op.drop_constraint('reservation_id_user_fkey', 'reservation', type_='foreignkey')

    # Hapus kolom FK lama dari tabel lain
    op.drop_column('feedback', 'id_users')
    op.drop_column('reservation', 'id_staff')
    op.drop_column('reservation', 'id_user')

    # Ganti primary key users
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.drop_column('users', 'id')
    op.alter_column('users', 'id_new', new_column_name='id')
    op.create_primary_key('users_pkey', 'users', ['id'])

    # Tambahkan ulang kolom FK (sekarang UUID)
    op.add_column('feedback', sa.Column('id_users', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True))
    op.add_column('reservation', sa.Column('id_staff', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True))
    op.add_column('reservation', sa.Column('id_user', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    # ### end Alembic commands ###
