"""perubahan nama status di reservasi

Revision ID: 9df251a2bdce
Revises: 6814be7b63fc
Create Date: 2025-10-13 13:50:11.245150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9df251a2bdce'
down_revision: Union[str, Sequence[str], None] = '6814be7b63fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE reservationstatusenum ADD value if not exists \'completed\'')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE reservationstatusenum_old AS ENUM ('pending', 'confirmed', 'cancelled');
        ALTER TABLE reservation ALTER COLUMN status TYPE reservationstatusenum_old USING status::text::reservationstatusenum_old;
        DROP TYPE reservationstatusenum;
        ALTER TYPE reservationstatusenum_old RENAME TO reservationstatusenum;
    """)
    # ### end Alembic commands ###
