"""Add username and password to customer

Revision ID: a42eec20c600
Revises: b8ce42b09948
Create Date: 2025-09-19 20:03:29.704008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42eec20c600'
down_revision: Union[str, Sequence[str], None] = 'b8ce42b09948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('customer', sa.Column('password', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password')
    op.drop_column('staff', 'username')
    op.drop_column('customer', 'password')
    op.drop_column('customer', 'username')
    # ### end Alembic commands ###
