"""Perubahan di tabel Customer penambahan role

Revision ID: b8ce42b09948
Revises: 551fe0550817
Create Date: 2025-09-19 19:05:45.198211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ce42b09948'
down_revision: Union[str, Sequence[str], None] = '551fe0550817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('role', sa.String(length=20), server_default='customer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'role')
    # ### end Alembic commands ###
