"""Revisi 2 table

Revision ID: c35b6a6b5a3e
Revises: 6b9ef73584a1
Create Date: 2025-10-06 06:21:39.897939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35b6a6b5a3e'
down_revision: Union[str, Sequence[str], None] = '6b9ef73584a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation','id_users', new_column_name='id_user')
    op.drop_constraint(op.f('reservation_id_users_fkey'), 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'users', ['id_user'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('id_users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key(op.f('reservation_id_users_fkey'), 'reservation', 'users', ['id_users'], ['id'])
    op.drop_column('reservation', 'id_user')
    # ### end Alembic commands ###
