"""mengubah status usrnm dan password jadi not nullable

Revision ID: cb1d7faa4896
Revises: a42eec20c600
Create Date: 2025-09-19 20:09:22.288698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1d7faa4896'
down_revision: Union[str, Sequence[str], None] = 'a42eec20c600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customer', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('staff', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('staff', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('staff', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
