"""Relasi

Revision ID: edd7135efae7
Revises: 5773be54885d
Create Date: 2025-09-23 14:09:02.182902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edd7135efae7'
down_revision: Union[str, Sequence[str], None] = '5773be54885d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meja', sa.Column('location', postgresql.ENUM('indoor', 'outdoor', 'vip', name='location_enum'), nullable=False))
    op.add_column('meja', sa.Column('status', postgresql.ENUM('tersedia', 'tidaktersedia', name='status_enum'), nullable=False))
    op.add_column('payment', sa.Column('method', postgresql.ENUM('cash', 'card', 'e_wallet', name='paymentmethodenum'), nullable=False))
    op.add_column('payment', sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='paymentstatusenum'), nullable=False))
    op.add_column('reservation', sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'cancelled', name='reservationstatusenum', ), nullable=False))
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'waiter', 'manager', 'reservationStaff', 'customer', name='roleenum', ), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('reservation', 'status')
    op.drop_column('payment', 'status')
    op.drop_column('payment', 'method')
    op.drop_column('meja', 'status')
    op.drop_column('meja', 'location')
    # ### end Alembic commands ###
