"""perbaiki relasi lagi

Revision ID: f7010154a7eb
Revises: f6c3ebb21bc1
Create Date: 2025-09-23 14:21:37.420321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7010154a7eb'
down_revision: Union[str, Sequence[str], None] = 'f6c3ebb21bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
